version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_debtapp
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DebtAppDB
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
